services:
  #If you need replicas of the containers, copy and past. At this moment,
  #DockerComposeV2's "replica" does not work as DockerComposeV1's
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: mongo
    image: mongo
    volumes:
      - sa_mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
      sa_mongo_data: {}



