services:
  #If you need replicas of the containers, copy and past. At this moment,
  #DockerComposeV2's "replica" does not work as DockerComposeV1's
  frontend:
    container_name: frontend
    build:
      context: frontend
    ports:
      - "4200:4200"
  backend:
    container_name: backend
    build:
      context: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    volumes:
      - sa_mongo_data:/data/db
    ports:
      - "27017:27017"
  db-init:
    container_name: db-init
    build:
      context: script
    depends_on:
      - mongodb
      - backend
volumes:
      sa_mongo_data: {}



